version: '3'

services:
  strapi:
    build: .
    ports:
      - '1337:1337'
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi-merakiweddingplanner
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: sandworm-proud-gradient
      MAILJET_PUBLIC_KEY: your_mailjet_public_key
      MAILJET_SECRET_KEY: your_mailjet_secret_key
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./config:/app/config
    restart: unless-stopped

  mysql:
    image: mysql:5.7.32
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: strapi-root-password
      MYSQL_DATABASE: strapi-merakiweddingplanner
      MYSQL_USER: strapi
      MYSQL_PASSWORD: sandworm-proud-gradient
    volumes:
      - strapi-mysql-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  strapi-mysql-data: 